### ISSUE TITLE
Computer not showing up in HomeKit App

### ISSUE THREAD

**Issue by stuarthenrywilson** [AlexGustafsson/homebridge-wol#19]
Hi, Im hoping you can help me (and that my question is not too stupid). I installed home bridge and have it working with my TP-Link switches. I thought your plugin sounded great so have installed it. I get no errors—everything seems to run fine—but my MacBook does not show up in the home kit app. I'm not sure what I am doing wrong!

My RPi is connected to my network via ethernet. 

My config file is as follows:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is a modified configuration file",

    "accessories": [
        {
            "accessory": "Computer",
            "name": "My Macbook",
            "mac": "XX:XX:XX:XX:XX:XX",
            "ip": "192.168.0.11",
            "pingInterval": 45,
            "wakeGraceTime": 90,
            "shutdownGraceTime": 15,
            "shutdownCommand": "ssh 192.168.1.51 sudo shutdown -h now"
         }
    ],

    "platforms": [
        {
            "platform" : "Hs100"
        }
    ]
}
`

I'm going to assume that the issue is with me and not your brilliant plugin so apologies if i shouldn't e posting this here. Any help would be much appreciated, though.

Thanks

Stuart

**Comment by AlexGustafsson** [comment]
Thank you for the compliments!

This is definitely the right place to ask for help since everything except this plugin seem to work. I'm happy to help.

I can't seem to find an issue. You've done everything right. Have you tried to restart the homebridge server? Is there any log output from homebridge? (Things to look for: "Computer is not registered by a plugin", "missing configuration" etc.)

**Comment by stuarthenrywilson** [comment]
Thanks for your quick reply. I've been running homebridge continually using the systemd service approach.  There are no outputs in that mode and I couldn't access the log last night for some reason.

This morning I tried running homebridge without using the service and it gives the following output:
`====================
[6/11/2017, 7:48:53 AM] ERROR LOADING PLUGIN homebridge-wol:
[6/11/2017, 7:48:53 AM] Error: Cannot find module './build/Release/raw'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wol/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[6/11/2017, 7:48:53 AM] ====================`

I installed the beta version which has removed this error so the plugin loads correctly. I can see my MacBook when I run homebridge without the systemd service—but when I switch to the service it disappears.

I'll figure this out soon—it must be something to do with my config file, although they appear to be in the correct place for both the standard run and the systemd rub.

Thanks again for your help.

**Comment by AlexGustafsson** [comment]
It seems to be some issue with a dependency of a dependency namely the raw sockets we currently use to ping devices. It could be that it failed to build during npm install, that the package author is having issues or a collection of other faults. Thank you for sharing the log so that others facing the same issue can resolve it.

About your other issue, there could have something to do with "the systemd" version not using the configuration you'd think. I believe that the first log homebridge makes when started contains information about the config file in use, but I'm uncertain. You can also verify when homebridge starts what accessories and plugins are loaded.

I hope you solve your issue. If it could help others, feel free to share your solution.

About the beta, be sure to reach out if anything crosses your mind regarding features, potential bugs etc.

**Comment by stuarthenrywilson** [comment]
Hey, sorry for the delay in getting back to you—I've been swamped with work. I'm just getting to grips with Linux systems and was getting myself confused with installing extra packages, trying different fixes, etc.

In the end, I re-flashed my Pi and reinstalled everything from scratch—it's working fine now. 

Thanks again!

**Comment by AlexGustafsson** [comment]
I'm happy you solved it!
