### ISSUE TITLE
WoL always on, although when the device is off

### ISSUE THREAD

**Issue by CyberChris79** [AlexGustafsson/homebridge-wol#205]
### Backstory

One upon a time a can't wake up my device, although it was online

### Issue

Since the latest version and jump from version 4 to 5 i recognized, that the plugin is always on, although when the device is off.
If i reboot the Homebridge everything works fine for a while, but after a few days i can't wake up the device again. It is offline and the Plugin shows me online. If i click to switch off, it switches back on. Just a reboot helps me to run the plugin again correctly

### Environment

```Markdown
- os and os version: Proxmox (latest) on Debian (latest)
- node version: v16.14.0
- homebridge version: v1.4.1
- homebridge-wol version: v5.0.1
```

### Configuration

{
    "name": "Workstation",
    "manufacturer": "homebridge-wol",
    "model": "NetworkDevice",
    "host": "IP:ADRESS",
    "pingInterval": 2,
    "pingsToChange": 5,
    "pingTimeout": 1,
    "pingCommandTimeout": 0,
    "mac": "XX:XX:XX:XX:XX:XX",
    "startCommandTimeout": 0,
    "wakeGraceTime": 45,
    "wakeCommandTimeout": 0,
    "shutdownGraceTime": 15,
    "shutdownCommandTimeout": 0,
    "logLevel": "Info",
    "returnEarly": true,
    "accessory": "NetworkDevice"
}

### Logs
This message is always repeating

[NetworkDevice] Device went from status "Online" to "Offline"

### Notes

**Comment by AlexGustafsson** [comment]
What device is it that you have? Have you upgraded that the device also since the last time it worked? Why I'm asking is that Apple products seem to be happy to respond to pings even when they seem to be off. I assume that other manufactures may do the same.

To try to progress this issue, the next time your device is off but the plugin says it's on, could you try to ping the device from the Homebridge server? If it replies, then you'll have to investigate the use of a ping command instead of pinging - as pinging is not reliable if the device always replies.

**Comment by CyberChris79** [comment]
@AlexGustafsson 
thank you for your answer.
I will try this next time and i will update the plugin now to the latest version

**Comment by AlexGustafsson** [comment]
Closing. If this is still an issue, feel free to reopen.
