### ISSUE TITLE
Dont wake after shutdown

### ISSUE THREAD

**Issue by Jamyz** [AlexGustafsson/homebridge-wol#242]
Something strange.
When i use Siri to sleep under windows 11 works fine.
But when i try to wake up again with Siri nothing. Or directly with the button on home app.

But if i shutdown without Siri (shurtdown normal under windows). And try to wake up with Siri works or button home app works.

So why when i shutdown with homebridge i cant wake up the PC ?

**Comment by Jamyz** [comment]
Ok i found.

In Docker Container startup.sh add :
apt-get update
apt-get install -y samba-common
apt-get install -y etherwake

in Wake configuration add
wakeonlan XX:XX:XX:XX:XX (your mac adress)

**Comment by AlexGustafsson** [comment]
Great that you solved the issue and thank's for sharing the solution. It can help others facing the same issue. Closing.

**Comment by Lechucico** [comment]
Same Issue here.

Where did you put wakeonlan XX:XX:XX:XX:XX (your mac adress)?

I've installed both packages (samba-common, etherwake) but still not working wake up if I shutdown using siri.

_Running on Raspbian GNU/Linux Bullseye (11)_

**Comment by Jamyz** [comment]
@Lechucico Hi!
If shutdown is correctly configured.
Maybe check if wol is active in your ethernet device and check if windows as ready to wol too.

**Comment by Lechucico** [comment]
@Jamyz Hello,

If I turn off computer manually, WOL package from homebridge-wol works correctly. Same for ssh shutdown, it works like a charm.

Problem comes when I try to WOL after ssh shutdown using Siri.

**Comment by Jamyz** [comment]
This what i have
![image](https://github.com/AlexGustafsson/homebridge-wol/assets/6177824/25b25dea-f54c-4137-b8a8-85038c0504d6)

Have you the same?

**Comment by Jamyz** [comment]
I have that
![image](https://github.com/AlexGustafsson/homebridge-wol/assets/6177824/12c37776-6737-425b-9630-5c79059a2d74)

**Comment by Lechucico** [comment]
This is the message that I've got If I try this command (I've changed my MAC for XX-XX-XX-XX-XX-XX):

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/410b0375-bf83-4d02-b98e-a498456269cf)

What version of wakeonlan do you have?

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/f39dadc7-3f6b-476f-bcfa-b31008a930da)

**Comment by Jamyz** [comment]
LOL.
I put XX:XX:XX:XX for exemple. Put your real mac adress.
i have 0.41 too.
also check this page [here](https://www.target-bravo.com/blog/2018/7/10/blog-headline-1-6y3tj-49m5s-7tbal-rbs4b)
the chapter "Windows Firewall" and "SERVICES"

**Comment by Lechucico** [comment]
@Jamyz I've replaced my real MAC just on the screenshot... Obviously, I have the real one configured.

**Comment by Jamyz** [comment]
You dont have log in homebridge when you try to wake up the computer?

**Comment by Lechucico** [comment]
I will explain it in the best possible way:

The computer can ALWAYS be turned on if I turn it off manually. If I turn it off using this plugin, It can't turn it on. I have been able to verify that this is the plugin's fault, because if I run the SSH command to turn it off manually, the plugin can then turn on the PC.

I am going to pass a series of LOGS that I have been able to compile proving that it is the fault of this plugin:

These logs are from when I shut down the computer with homebridge:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/c53cfa2f-2341-469e-8540-648ad51c9111)

The problem comes, that the plugin stays stuck until I don't turn it on manually, which is when the log that I mark below appears:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/dd035092-0da3-4f80-ba70-244754e60df2)

Until the "Waiting for shutdown grace time" appears, the plugin becomes unresponsive, and it doesn't appear until I turn on the PC manually. No matter how much I click to turn on the computer, no logs appear.

If I turn the PC off manually, I can turn it on and the logs appear as they should:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/12977034-a63e-4eee-9207-eac51d12624b)

See if anyone can help me.

**Comment by Jamyz** [comment]
Hi @Lechucico  hablas español ?

**Comment by Lechucico** [comment]
> Hi @Lechucico hablas español ?

Sí

**Comment by Jamyz** [comment]
Una pregunta ? Que Ordenador usas ? Es bajo Linux o Windows el que deseas encender ?

**Comment by Lechucico** [comment]
> Una pregunta ? Que Ordenador usas ? Es bajo Linux o Windows el que deseas encender ?

Homebridge funciona en una raspberry pi. El ordenador que intento encender funciona sobre Windows.

He abierto una incidencia aquí https://github.com/AlexGustafsson/homebridge-wol/issues/259 con toda la información.
