### ISSUE TITLE
How can I do this step?

### ISSUE THREAD

**Issue by giovenuta** [AlexGustafsson/homebridge-wol#38]
Hi!
I'm noobs in programming.
I have this problem, how can I do this step?

**Note: homebridge-wol requires extra permissions due to the use of pinging and magic packages. Start homebridge with sudo: sudo homebridge or change capabilities accordingly (setcap cap_net_raw=pe /path/to/bin/node). Systemd users can add the following lines to the [Service] section of homebridge's unit file (or create a drop-in if unit is packaged by your distro) to achieve this in a more secure way:

CapabilityBoundingSet=CAP_NET_RAW
AmbientCapabilities=CAP_NET_RAW_**

There is someone who can help me step by step?( I can only use terminal or hoimebridge app for iOS)
Thanks so much,

Gio

**Comment by AlexGustafsson** [comment]
It is not a necessary step, so if you’re comfortable with it you can choose to run homebridge with sudo rights: `sudo homebridge` instead. One could argue it’s less secure since it gives homebridge all rights instead of only the cap_net_raw permission.

**Comment by giovenuta** [comment]
Thanks!!

**Comment by giuse93or** [comment]
Hi alexGustafsson, i use your plugin for wake up windows, but i can't see the status or i can't shutdown
Do i need extra permissions due to the use of pinging?
While i was installing I launch homebridge with sudo and everything went ok. Next I move the json to the dir of Hombridge (launched as a service on startup of Raspberry), now I can wake up my pc, but I can't see the status or shutdown
I'm using net rpc command... Should i use for account ****@live.com or only the ****?
How can i set Extra permission? I'm thinking it is the problem for both

**Comment by AlexGustafsson** [comment]
@giuse93or The issue #34 might have some information you're after. 

Since you're already launching homebridge with sudo, you already give full rights to homebridge - so there is no issue with pinging itself. The status should show regardless if you're able to actually shut the device off. Make sure you've configured the right IP address.

As for shutting the computer down, I think you need to explicitly enable the service on Windows as the `net rpc` commands won't actually work otherwise.

During my (somewhat limited) research of the subject, it seems like it's hard to do it right. I would not recommend you to enable `net rpc` commands due to security issues. However, there is a guide here: http://blog.sip2serve.com/post/155565656901/shutdown-windows-10-remotely.

I'm not actually sure what account you're supposed to use, but I think it's the full account name (email). 

If you have further issues, open a separate issue and I'll try to help you there!
