### ISSUE TITLE
Windows wake

### ISSUE THREAD

**Issue by perrintong325** [AlexGustafsson/homebridge-wol#68]
Hi,

I'm new to homebridge so this might sound quite idiotic, but can someone please help me with the config?

For windows what command should i use for the wake command? Also is there a sleep instead of shutdown? Here are my codes but nth seem to work
{
      "accessory": "NetworkDevice",
      "name": "Desktop",
      "mac": "xxxxxxx",
      "ip": "192.168.188.101/24",
      "pingInterval": 45,
      "wakeGraceTime": 10,
      "shutdownGraceTime": 15,
      "shutdownCommand": "net rpc shutdown --ipaddress 192.168.188.101/24 --user xxx%xxx"
    }

thx

**Comment by AlexGustafsson** [comment]
Hi!

You don't necessarily need a wake command since most Windows PCs can be configured to start when they receive a "magic packet" using Wake on Lan. Configuring the MAC address is sufficient for this use case.

As for shutdown command, I'm afraid you'll have to do some googling in order to find a solution. I don't know about a "net rpc sleep" command.

If you have further questions, feel free to reopen the issue!
