### ISSUE TITLE
Not shutting down

### ISSUE THREAD

**Issue by Frankdoc** [AlexGustafsson/homebridge-wol#78]
Hi,
The wake on lan works, but the shutting down does not.
Config:
"shutdownCommand": "sudo net rpc shutdown --ipaddress 192.168.1.11 --user user%password"

When I check the logs:
Command failed
homebridge_1  | We trust you have received the usual lecture from the local System
homebridge_1  | Administrator. It usually boils down to these three things:
homebridge_1  |
homebridge_1  |     #1) Respect the privacy of others.
homebridge_1  |     #2) Think before you type.
homebridge_1  |     #3) With great power comes great responsibility.
homebridge_1  |
homebridge_1  | sudo: no tty present and no askpass program specified

How do I fix this? When I enter the command in putty ( as user pi) it does work, so I assume it's something with priviliges/not entering password.
I also noticed WOL didn't work after I remote shutdown: coincidence?

**Comment by AlexGustafsson** [comment]
The command fails because the remote server tries to authenticate you via an interactive prompt for your password. That can’t happen, however, since the command is run non-interactively (hence lack of a TTY). It works with PuTTY since it allows for interactive authentication. You will need to pass in the password through arguments somehow or remove the password. Make sure that the syntax for how you’re passing in the user and password is correct. I haven’t net rpc myself, so you’ll need to Google it.

As for the other issue, it’s likely another issue, but it should already be mentioned in other issues and potentially already have a fix. You can try to install the plugin from the master branch directly and not through NPM to get the latest version.

Feel free to reopen if you feel that the issue is not solved. Any discussion can still take place here, however. Good luck!

**Comment by Frankdoc** [comment]
Hi Alex,

I tried following this guide:
https://stackoverflow.com/questions/21659637/how-to-fix-sudo-no-tty-present-and-no-askpass-program-specified-error

To allow the net rpc command to be executed as sudo without password. But I'm having issues setting this up, probably because I'm not using the right filepath. Any idea?

**Comment by AlexGustafsson** [comment]
Sorry, I have no experience with net rpc, so I can't help you. I generally recommend against using net rpc due to security concerns. I think you may have more success with SSH, which should be available on newer versions of Windows 10. It allows for secure key-based authentication.
